"""durable_request_outbox

Revision ID: 624d7840c228
Revises: c327f8a76e79
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '624d7840c228'
down_revision: Union[str, None] = 'c327f8a76e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox', sa.Column('payload', sa.JSON(), nullable=True))
    op.add_column('outbox', sa.Column('payload_hash', sa.String(length=64), nullable=True))
    op.add_column('outbox', sa.Column('claim_token', sa.String(length=36), nullable=True))
    op.add_column('outbox', sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('outbox', sa.Column('suppressed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('service_requests', sa.Column('service_postal_code', sa.String(length=5), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_requests', 'service_postal_code')
    op.drop_column('outbox', 'suppressed')
    op.drop_column('outbox', 'lease_until')
    op.drop_column('outbox', 'claim_token')
    op.drop_column('outbox', 'payload_hash')
    op.drop_column('outbox', 'payload')
    # ### end Alembic commands ###
