#!/usr/bin/env python3
"""Package the selected logo for iOS, Android and web.

This packages existing artwork; it does not generate or redraw the logo.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
APP = ROOT / 'app'
SOURCE = APP / 'assets/brand/estimoto-plus-icon.png'

# Android's scalable companion of the selected master: white E, separate navy
# centered plus, and the small teal brand dot. Coordinates use a 1024px canvas.
MARK_PATHS = """        <path android:fillColor="#FFFFFF"
            android:pathData="M125,278 H529 V382 H245 V454 H502 V552 H245 V625 H544 V725 H125 Z" />
        <path android:fillColor="#00B8A9"
            android:pathData="M724,370 A66,66 0,1 1,592 370 A66,66 0,1 1,724 370 Z" />
        <path android:fillColor="#0D3F7A"
            android:pathData="M731,426 H803 V498 H881 V570 H803 V646 H731 V570 H656 V498 H731 Z" />"""


def android_launcher():
    resources = APP / 'android/app/src/main/res'
    # A 69dp master-art canvas keeps every painted corner inside the centered
    # 66dp circular safe area of Android's 108dp adaptive layer. The legacy
    # vector is the same visible 72dp viewport, already masked to a circle.
    scale = 69 / 1024
    for name, viewport, translate, background in [
        ('drawable/ic_launcher_foreground.xml', 108, 19.5, ''),
        ('mipmap-anydpi-v21/ic_launcher.xml', 72, 1.5,
         '    <path android:fillColor="@color/ic_launcher_background" '
         'android:pathData="M72,36 A36,36 0,1 1,0 36 A36,36 0,1 1,72 36 Z" />\n'),
    ]:
        target = resources / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/sync_app_icons.py (Android launcher mode). -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{viewport}dp" android:height="{viewport}dp"
    android:viewportWidth="{viewport}" android:viewportHeight="{viewport}">
{background}    <group android:scaleX="{scale}" android:scaleY="{scale}"
        android:translateX="{translate}" android:translateY="{translate}">
{MARK_PATHS}
    </group>
</vector>
''')
    adaptive = resources / 'mipmap-anydpi-v26/ic_launcher.xml'
    adaptive.parent.mkdir(parents=True, exist_ok=True)
    adaptive.write_text('''<?xml version="1.0" encoding="utf-8"?>
<!-- Android applies the launcher's circle, squircle or other adaptive mask. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
''')
    (resources / 'values/launcher_icons.xml').write_text('''<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ic_launcher_background">#58A4E5</color>
    <!-- Both entry points resolve to the round legacy or adaptive resource. -->
    <item type="mipmap" name="ic_launcher_round">@mipmap/ic_launcher</item>
</resources>
''')
    # Supported Android versions use the vector/adaptive resources above. Do
    # not leave square density copies for tools to restore in a later sync.
    for density in ('mdpi', 'hdpi', 'xhdpi', 'xxhdpi', 'xxxhdpi'):
        (resources / f'mipmap-{density}/ic_launcher.png').unlink(missing_ok=True)


def resize(destination, pixels):
    destination.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(['sips', '-z', str(pixels), str(pixels), str(SOURCE), '--out', str(destination)],
                   check=True, stdout=subprocess.DEVNULL)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--android-launcher-only', action='store_true',
                        help='Update Android launchers; preserve master, launch, iOS and web artwork.')
    args = parser.parse_args()
    android_launcher()
    if args.android_launcher_only:
        print('Updated Android adaptive and circular launcher resources. Master and iOS artwork unchanged.')
        return
    # A new URL is required when the artwork changes: returning browsers may
    # still have a fresh HTTP-cache entry for the previous stable filename.
    artwork = SOURCE.read_bytes()
    asset = f'estimoto-plus-icon-{hashlib.sha256(artwork).hexdigest()[:16]}.png'
    (SOURCE.parent / asset).write_bytes(artwork)
    (APP / 'lib/brand_assets.dart').write_text(
        '// Generated by scripts/sync_app_icons.py.\n'
        f"const plusIconAsset = 'assets/brand/{asset}';\n")
    pubspec = APP / 'pubspec.yaml'
    manifest = re.sub(r'(?m)^    - assets/brand/estimoto-plus-icon-[a-f0-9]{16}\.png\n', '', pubspec.read_text())
    anchor = '    - assets/brand/estimoto-plus-icon.png\n'
    if manifest.count(anchor) != 1:
        raise ValueError('Expected the master brand asset once in pubspec.yaml')
    pubspec.write_text(manifest.replace(anchor, anchor + f'    - assets/brand/{asset}\n'))
    icons = APP / 'ios/Runner/Assets.xcassets/AppIcon.appiconset'
    for item in json.loads((icons / 'Contents.json').read_text())['images']:
        if item.get('filename'):
            pixels = round(float(item['size'].split('x')[0]) * float(item['scale'].rstrip('x')))
            resize(icons / item['filename'], pixels)
    launch = APP / 'ios/Runner/Assets.xcassets/LaunchImage.imageset'
    for scale in (1, 2, 3):
        resize(launch / f'LaunchImage{"" if scale == 1 else f"@{scale}x"}.png', 120 * scale)
    for density, scale in [('mdpi', 1), ('hdpi', 1.5), ('xhdpi', 2), ('xxhdpi', 3), ('xxxhdpi', 4)]:
        resources = APP / 'android/app/src/main/res'
        resize(resources / f'drawable-{density}/launch_image.png', round(120 * scale))
    resize(APP / 'web/favicon.png', 32)
    for size in (192, 512):
        resize(APP / f'web/icons/Icon-{size}.png', size)
        # The square logo fits within the maskable safe area after platform padding.
        target = APP / f'web/icons/Icon-maskable-{size}.png'
        resize(target, round(size * 0.66))
        subprocess.run(['sips', '--padToHeightWidth', str(size), str(size), '--padColor', '58A4E5', str(target)],
                       check=True, stdout=subprocess.DEVNULL)
    print('Updated iOS, Android, launch and web assets from the selected Estimoto + icon.')


if __name__ == '__main__':
    main()
